;; -*- Mode: Emacs-Lisp ; Coding: utf-8 -*-

(add-to-list 'load-path "~/.emacs.d")
(add-to-list 'load-path "~/.emacs.d/elisp")
(add-to-list 'load-path "~/.emacs.d/auto-install")

(load "init-base")
(load "init-coding")
(load "init-color-theme")
(load "init-kill-summary")
(load "init-org")
(load "init-speedbar")
(load "init-tags")
(load "init-term")
(load "init-tramp")
(load "init-vc")
(load "init-windows")
(load "init-auto-install")
(load "init-anything")
(load "init-flymake")
